Container System: utility_module::formatter Class Reference
utility_module::formatter Class Reference
Simple formatter wrapper around std::format.
#include <formatter.h>
Static Public Member Functions
template<typename... Args>
static std::string format (const std::string &format_str, Args &&... args)
template<typename OutputIt , typename... Args>
static void format_to (OutputIt out, const std::string &format_str, Args &&... args)
static std::string format (const std::string &format_str)
Static Private Member Functions
template<typename T >
static void replace_next (std::string &str, T &&value)
Detailed Description
Simple formatter wrapper around std::format.
Uses std::vformat when full C++20 <format> support is available (GCC 13+, MSVC 19.29+). Falls back to ostringstream-based placeholder substitution on compilers with incomplete <format> (e.g. Apple Clang).
Definition at line 54 of file formatter.h.
Member Function Documentation
format() [1/2]
static std::string utility_module::formatter::format (const std::string & format_str) inline static
Definition at line 94 of file formatter.h.
{
        return format_str;
    }
format() [2/2]
template<typename... Args> static std::string utility_module::formatter::format (const std::string & format_str, Args &&... args) inline static
Definition at line 80 of file formatter.h.
{
        std::string result = format_str;
        (replace_next(result, std::forward<Args>(args)), ...);
        return result;
    }
References replace_next().
Referenced by format_to().
format_to()
template<typename OutputIt , typename... Args> static void utility_module::formatter::format_to (OutputIt out, const std::string & format_str, Args &&... args) inline static
Definition at line 87 of file formatter.h.
{
        std::string result = format(format_str, std::forward<Args>(args)...);
        std::copy(result.begin(), result.end(), out);
    }
References format().
replace_next()
template<typename T > static void utility_module::formatter::replace_next (std::string & str, T && value) inline static private
Definition at line 101 of file formatter.h.
{
        auto pos = str.find("{}");
        if (pos == std::string::npos) return;
        std::ostringstream oss;
        oss << std::forward<T>(value);
        str.replace(pos, 2, oss.str());
    }
Referenced by format().
The documentation for this class was generated from the following file:
utilities/core/formatter.h