Container System: kcenon::container::internal Namespace Reference
kcenon::container::internal Namespace Reference
Classes
class fixed_block_pool
class pool_allocator
Thread-local pool manager for value_container allocations.
struct pool_allocator_stats
Extended pool statistics with hit/miss tracking.
struct pool_size_class
Size class thresholds for pool allocation.
Functions
template<typename T , typename... Args>
T * pool_allocate (Args &&... args) noexcept
Allocate and construct an object using pool allocation.
template<typename T >
void pool_deallocate (T *ptr) noexcept
Destroy and deallocate an object allocated with pool_allocate.
template<typename T >
constexpr bool is_pool_allocatable () noexcept
Check if a type is suitable for pool allocation.
constexpr int get_size_class (std::size_t size) noexcept
Get the size class for a given size.
Function Documentation
get_size_class()
constexpr int kcenon::container::internal::get_size_class (std::size_t size) inline constexpr noexcept
Get the size class for a given size.
Parameters
size Size in bytes
Returns
0 for small, 1 for medium, 2 for large
Definition at line 257 of file pool_allocator.h.
{
    if (size <= pool_size_class::small_threshold) {
        return 0;
    } else if (size <= pool_size_class::medium_threshold) {
        return 1;
    }
    return 2;
}
References kcenon::container::internal::pool_size_class::medium_threshold, and kcenon::container::internal::pool_size_class::small_threshold.
is_pool_allocatable()
template<typename T > constexpr bool kcenon::container::internal::is_pool_allocatable () constexpr noexcept
Check if a type is suitable for pool allocation.
Template Parameters
T Type to check
Returns
true if type fits in pool (size <= medium_threshold)
Definition at line 248 of file pool_allocator.h.
{
    return sizeof(T) <= pool_size_class::medium_threshold;
}
References kcenon::container::internal::pool_size_class::medium_threshold.
pool_allocate()
template<typename T , typename... Args> T * kcenon::container::internal::pool_allocate (Args &&... args) noexcept
Allocate and construct an object using pool allocation.
Template Parameters
T Type to construct
Args Constructor argument types
Parameters
args Constructor arguments
Returns
Pointer to constructed object, or nullptr on failure
Definition at line 210 of file pool_allocator.h.
{
    static_assert(std::is_nothrow_destructible_v<T>,
                  "pool_allocate requires nothrow destructible types");
    void* ptr = pool_allocator::instance().allocate(sizeof(T));
    if (!ptr) {
        return nullptr;
    }
    try {
        return new (ptr) T(std::forward<Args>(args)...);
    } catch (...) {
        pool_allocator::instance().deallocate(ptr, sizeof(T));
        return nullptr;
    }
}
References kcenon::container::internal::pool_allocator::allocate(), kcenon::container::internal::pool_allocator::deallocate(), and kcenon::container::internal::pool_allocator::instance().
pool_deallocate()
template<typename T > void kcenon::container::internal::pool_deallocate (T * ptr) noexcept
Destroy and deallocate an object allocated with pool_allocate.
Template Parameters
T Type of object
Parameters
ptr Pointer to object
Definition at line 233 of file pool_allocator.h.
{
    if (!ptr) {
        return;
    }
    ptr->~T();
    pool_allocator::instance().deallocate(ptr, sizeof(T));
}
References kcenon::container::internal::pool_allocator::deallocate(), and kcenon::container::internal::pool_allocator::instance().