Container System: kcenon::container::async::async_executor_context Class Reference
kcenon::container::async::async_executor_context Class Reference
Global executor for async operations.
#include <thread_pool_executor.h>
Public Member Functions
void set_executor (executor_ptr executor)
Set the global executor.
executor_ptr get_executor () const
Get the global executor.
bool has_executor () const
Check if an executor is configured.
void clear_executor ()
Clear the global executor.
Static Public Member Functions
static async_executor_context & instance ()
Get the singleton instance.
Private Member Functions
async_executor_context ()=default
Private Attributes
executor_ptr executor_ {}
Detailed Description
Global executor for async operations.
When set, async operations will use this executor instead of creating individual threads. This improves performance by reusing threads from a pool.
Definition at line 212 of file thread_pool_executor.h.
Constructor & Destructor Documentation
async_executor_context()
kcenon::container::async::async_executor_context::async_executor_context () private default
Member Function Documentation
clear_executor()
void kcenon::container::async::async_executor_context::clear_executor () inline
Clear the global executor.
Definition at line 257 of file thread_pool_executor.h.
        {
#ifdef KCENON_HAS_COMMON_SYSTEM
            executor_ = nullptr;
#endif
        }
References executor_.
get_executor()
executor_ptr kcenon::container::async::async_executor_context::get_executor () const inline nodiscard
Get the global executor.
Returns
The current executor, or nullptr if not set
Definition at line 237 of file thread_pool_executor.h.
        {
            return executor_;
        }
References executor_.
has_executor()
bool kcenon::container::async::async_executor_context::has_executor () const inline nodiscard
Check if an executor is configured.
Definition at line 245 of file thread_pool_executor.h.
        {
#ifdef KCENON_HAS_COMMON_SYSTEM
            return executor_ != nullptr;
#else
            return false;
#endif
        }
References executor_.
instance()
static async_executor_context & kcenon::container::async::async_executor_context::instance () inline static
Get the singleton instance.
Definition at line 218 of file thread_pool_executor.h.
        {
            static async_executor_context instance;
            return instance;
        }
References instance().
Referenced by kcenon::container::async::executor_context_guard::executor_context_guard(), instance(), and kcenon::container::async::executor_context_guard::~executor_context_guard().
set_executor()
void kcenon::container::async::async_executor_context::set_executor (executor_ptr executor) inline
Set the global executor.
Parameters
executor The executor to use for async operations
Definition at line 228 of file thread_pool_executor.h.
        {
            executor_ = std::move(executor);
        }
References executor_.
Referenced by kcenon::container::async::executor_context_guard::executor_context_guard(), and kcenon::container::async::executor_context_guard::~executor_context_guard().
Member Data Documentation
executor_
executor_ptr kcenon::container::async::async_executor_context::executor_ {} private
Definition at line 266 of file thread_pool_executor.h.
{};
Referenced by clear_executor(), get_executor(), has_executor(), and set_executor().
The documentation for this class was generated from the following file:
internal/async/thread_pool_executor.h