Container System: kcenon::container::value_view Class Reference
kcenon::container::value_view Class Reference
Zero-copy value view for efficient read access.
#include <value_view.h>
Public Member Functions
value_view (const char *name_data, size_t name_length, const char *value_data, size_t value_length, value_types type) noexcept
Construct a value view.
std::string_view name () const noexcept
Get the value name as string_view (zero-copy)
value_types type () const noexcept
Get the value type.
std::string_view as_string_view () const noexcept
Get string value as string_view (zero-copy)
std::string as_string () const
Get string value as owned copy.
template<typename T >
std::optional< T > as () const noexcept
Type-safe value extraction.
bool is_null () const noexcept
Check if this is a null value.
const char * data () const noexcept
Get raw value data pointer.
size_t size () const noexcept
Get value data length.
Private Member Functions
template<typename T >
std::optional< T > parse_integral () const noexcept
Parse integral value from string data.
template<typename T >
std::optional< T > parse_floating () const noexcept
Parse floating-point value from string data.
Static Private Member Functions
static bool is_integral_type (value_types t) noexcept
Check if type is an integral type.
Private Attributes
const char * name_data_
size_t name_length_
const char * value_data_
size_t value_length_
value_types type_
Detailed Description
Zero-copy value view for efficient read access.
value_view provides a non-owning view into serialized data, enabling zero-copy access to string and numeric values. The underlying buffer must remain valid for the lifetime of the view.
Key features:
Zero-copy string access via string_view
Type-safe numeric extraction
Minimal memory overhead (just pointers and metadata)
No heap allocations for primitive types
Definition at line 55 of file value_view.h.
Constructor & Destructor Documentation
value_view()
kcenon::container::value_view::value_view (const char * name_data, size_t name_length, const char * value_data, size_t value_length, value_types type) inline noexcept
Construct a value view.
Parameters
name_data Pointer to the name string data
name_length Length of the name string
value_data Pointer to the value data
value_length Length of the value data
type The value type
Definition at line 66 of file value_view.h.
        : name_data_(name_data)
        , name_length_(name_length)
        , value_data_(value_data)
        , value_length_(value_length)
        , type_(type)
    {}
Member Function Documentation
as()
template<typename T > std::optional< T > kcenon::container::value_view::as () const inline nodiscard noexcept
Type-safe value extraction.
Template Parameters
T The expected value type
Returns
std::optional containing the value if type matches
Definition at line 117 of file value_view.h.
    {
        if constexpr (std::is_same_v<T, std::string_view>) {
            if (type_ == value_types::string_value ||
                type_ == value_types::bytes_value) {
                return as_string_view();
            }
            return std::nullopt;
        }
        else if constexpr (std::is_same_v<T, std::string>) {
            if (type_ == value_types::string_value ||
                type_ == value_types::bytes_value) {
                return as_string();
            }
            return std::nullopt;
        }
        else if constexpr (std::is_same_v<T, bool>) {
            if (type_ == value_types::bool_value && value_length_ > 0) {
                return (value_data_[0] == 't' || value_data_[0] == 'T' ||
                        value_data_[0] == '1');
            }
            return std::nullopt;
        }
        else if constexpr (std::is_integral_v<T>) {
            return parse_integral<T>();
        }
        else if constexpr (std::is_floating_point_v<T>) {
            return parse_floating<T>();
        }
        else {
            return std::nullopt;
        }
    }
References as_string(), as_string_view(), parse_floating(), parse_integral(), type_, value_data_, and value_length_.
as_string()
std::string kcenon::container::value_view::as_string () const inline nodiscard
Get string value as owned copy.
Returns
Copied string
Definition at line 106 of file value_view.h.
    {
        return {value_data_, value_length_};
    }
References value_data_, and value_length_.
Referenced by as().
as_string_view()
std::string_view kcenon::container::value_view::as_string_view () const inline nodiscard noexcept
Get string value as string_view (zero-copy)
Returns
string_view pointing into original buffer
Note
Only valid for string_value and bytes_value types
Definition at line 97 of file value_view.h.
    {
        return {value_data_, value_length_};
    }
References value_data_, and value_length_.
Referenced by as().
data()
const char * kcenon::container::value_view::data () const inline nodiscard noexcept
Get raw value data pointer.
Definition at line 162 of file value_view.h.
    {
        return value_data_;
    }
References value_data_.
is_integral_type()
static bool kcenon::container::value_view::is_integral_type (value_types t) inline static nodiscard private noexcept
Check if type is an integral type.
Definition at line 245 of file value_view.h.
    {
        switch (t) {
            case value_types::short_value:
            case value_types::ushort_value:
            case value_types::int_value:
            case value_types::uint_value:
            case value_types::long_value:
            case value_types::ulong_value:
            case value_types::llong_value:
            case value_types::ullong_value:
                return true;
            default:
                return false;
        }
    }
Referenced by parse_integral().
is_null()
bool kcenon::container::value_view::is_null () const inline nodiscard noexcept
Check if this is a null value.
Definition at line 154 of file value_view.h.
    {
        return type_ == value_types::null_value;
    }
References type_.
name()
std::string_view kcenon::container::value_view::name () const inline nodiscard noexcept
Get the value name as string_view (zero-copy)
Definition at line 79 of file value_view.h.
    {
        return {name_data_, name_length_};
    }
References name_data_, and name_length_.
parse_floating()
template<typename T > std::optional< T > kcenon::container::value_view::parse_floating () const inline nodiscard private noexcept
Parse floating-point value from string data.
Definition at line 213 of file value_view.h.
    {
        if (type_ != value_types::float_value &&
            type_ != value_types::double_value) {
            return std::nullopt;
        }
        if (value_length_ == 0) {
            return std::nullopt;
        }
        char* end = nullptr;
        std::string temp(value_data_, value_length_);
        if constexpr (std::is_same_v<T, float>) {
            float val = std::strtof(temp.c_str(), &end);
            if (end != temp.c_str() + temp.size()) {
                return std::nullopt;
            }
            return val;
        } else {
            double val = std::strtod(temp.c_str(), &end);
            if (end != temp.c_str() + temp.size()) {
                return std::nullopt;
            }
            return static_cast<T>(val);
        }
    }
References type_, value_data_, and value_length_.
Referenced by as().
parse_integral()
template<typename T > std::optional< T > kcenon::container::value_view::parse_integral () const inline nodiscard private noexcept
Parse integral value from string data.
Definition at line 180 of file value_view.h.
    {
        if (!is_integral_type(type_)) {
            return std::nullopt;
        }
        if (value_length_ == 0) {
            return std::nullopt;
        }
        // Use strtoll/strtoull for parsing
        char* end = nullptr;
        std::string temp(value_data_, value_length_);
        if constexpr (std::is_signed_v<T>) {
            long long val = std::strtoll(temp.c_str(), &end, 10);
            if (end != temp.c_str() + temp.size()) {
                return std::nullopt;
            }
            return static_cast<T>(val);
        } else {
            unsigned long long val = std::strtoull(temp.c_str(), &end, 10);
            if (end != temp.c_str() + temp.size()) {
                return std::nullopt;
            }
            return static_cast<T>(val);
        }
    }
References is_integral_type(), type_, value_data_, and value_length_.
Referenced by as().
size()
size_t kcenon::container::value_view::size () const inline nodiscard noexcept
Get value data length.
Definition at line 170 of file value_view.h.
    {
        return value_length_;
    }
References value_length_.
type()
value_types kcenon::container::value_view::type () const inline nodiscard noexcept
Get the value type.
Definition at line 87 of file value_view.h.
    {
        return type_;
    }
References type_.
Member Data Documentation
name_data_
const char* kcenon::container::value_view::name_data_ private
Definition at line 262 of file value_view.h.
Referenced by name().
name_length_
size_t kcenon::container::value_view::name_length_ private
Definition at line 263 of file value_view.h.
Referenced by name().
type_
value_types kcenon::container::value_view::type_ private
Definition at line 266 of file value_view.h.
Referenced by as(), is_null(), parse_floating(), parse_integral(), and type().
value_data_
const char* kcenon::container::value_view::value_data_ private
Definition at line 264 of file value_view.h.
Referenced by as(), as_string(), as_string_view(), data(), parse_floating(), and parse_integral().
value_length_
size_t kcenon::container::value_view::value_length_ private
Definition at line 265 of file value_view.h.
Referenced by as(), as_string(), as_string_view(), parse_floating(), parse_integral(), and size().
The documentation for this class was generated from the following file:
internal/value_view.h