Container System: kcenon::container::async::detail Namespace Reference
kcenon::container::async::detail Namespace Reference
Classes
struct async_awaitable
Awaitable that runs work in a separate thread.
struct async_state
Shared state for async operations.
struct executor_awaitable
Awaitable that runs work using an executor or fallback thread.
struct executor_state
Shared state for executor-based async operations.
struct generator_promise
Promise type for generator.
struct promise_base
Base promise type with common functionality.
struct promise_type
Promise type for value-returning tasks.
struct promise_type< void >
Promise type for void-returning tasks.
Functions
template<typename F >
auto make_async_awaitable (F &&func) -> async_awaitable< std::invoke_result_t< F > >
template<typename F >
auto make_executor_awaitable (F &&func, executor_ptr executor) -> executor_awaitable< std::invoke_result_t< F > >
Helper to create executor awaitable.
Function Documentation
make_async_awaitable()
template<typename F > auto kcenon::container::async::detail::make_async_awaitable (F && func) -> async_awaitable<std::invoke_result_t<F>>
Definition at line 169 of file async_container.h.
        {
            using result_type = std::invoke_result_t<F>;
            return async_awaitable<result_type>(std::forward<F>(func));
        }
Referenced by kcenon::container::async::async_container::deserialize_async(), kcenon::container::async::async_container::deserialize_streaming(), kcenon::container::async::async_container::deserialize_string_async(), kcenon::container::async::async_container::load_async(), kcenon::container::async::read_file_async(), kcenon::container::async::async_container::save_async(), kcenon::container::async::async_container::serialize_async(), kcenon::container::async::async_container::serialize_string_async(), and kcenon::container::async::write_file_async().
make_executor_awaitable()
template<typename F > auto kcenon::container::async::detail::make_executor_awaitable (F && func, executor_ptr executor) -> executor_awaitable<std::invoke_result_t<F>>
Helper to create executor awaitable.
Definition at line 223 of file thread_pool_executor.h.
        {
            using result_type = std::invoke_result_t<F>;
            return executor_awaitable<result_type>(
                std::forward<F>(func), std::move(executor));
        }