Container System: kcenon::container::async::executor_context_guard Class Reference
kcenon::container::async::executor_context_guard Class Reference
RAII guard for setting executor context.
#include <thread_pool_executor.h>
Public Member Functions
executor_context_guard (executor_ptr executor)
~executor_context_guard ()
executor_context_guard (const executor_context_guard &)=delete
executor_context_guard & operator= (const executor_context_guard &)=delete
Private Attributes
executor_ptr previous_
Detailed Description
RAII guard for setting executor context.
Sets the executor on construction and restores the previous executor on destruction.
{
    executor_context_guard guard(my_executor);
    // All async operations in this scope use my_executor
    auto result = co_await container.serialize_async();
}
// Previous executor restored
Definition at line 312 of file thread_pool_executor.h.
Constructor & Destructor Documentation
executor_context_guard() [1/2]
kcenon::container::async::executor_context_guard::executor_context_guard (executor_ptr executor) inline explicit
Definition at line 315 of file thread_pool_executor.h.
            : previous_(async_executor_context::instance().get_executor())
        {
            async_executor_context::instance().set_executor(std::move(executor));
        }
References kcenon::container::async::async_executor_context::instance(), and kcenon::container::async::async_executor_context::set_executor().
~executor_context_guard()
kcenon::container::async::executor_context_guard::~executor_context_guard () inline
Definition at line 321 of file thread_pool_executor.h.
        {
            async_executor_context::instance().set_executor(std::move(previous_));
        }
References kcenon::container::async::async_executor_context::instance(), previous_, and kcenon::container::async::async_executor_context::set_executor().
executor_context_guard() [2/2]
kcenon::container::async::executor_context_guard::executor_context_guard (const executor_context_guard &) delete
Member Function Documentation
operator=()
executor_context_guard & kcenon::container::async::executor_context_guard::operator= (const executor_context_guard &) delete
Member Data Documentation
previous_
executor_ptr kcenon::container::async::executor_context_guard::previous_ private
Definition at line 330 of file thread_pool_executor.h.
Referenced by ~executor_context_guard().
The documentation for this class was generated from the following file:
internal/async/thread_pool_executor.h