Container System: kcenon::container::epoch_guard Class Reference
kcenon::container::epoch_guard Class Reference
RAII guard for epoch critical section.
#include <epoch_manager.h>
Public Member Functions
epoch_guard () noexcept
Enter critical section.
~epoch_guard () noexcept
Exit critical section.
epoch_guard (const epoch_guard &)=delete
epoch_guard & operator= (const epoch_guard &)=delete
epoch_guard (epoch_guard &&)=delete
epoch_guard & operator= (epoch_guard &&)=delete
Detailed Description
RAII guard for epoch critical section.
Automatically enters critical section on construction and exits on destruction.
{
    epoch_guard guard;
    // ... access lock-free data structure ...
} // automatically exits critical section
Definition at line 326 of file epoch_manager.h.
Constructor & Destructor Documentation
epoch_guard() [1/3]
kcenon::container::epoch_guard::epoch_guard () inline noexcept
Enter critical section.
Definition at line 332 of file epoch_manager.h.
{
            epoch_manager::instance().enter_critical();
        }
References kcenon::container::epoch_manager::enter_critical(), and kcenon::container::epoch_manager::instance().
~epoch_guard()
kcenon::container::epoch_guard::~epoch_guard () inline noexcept
Exit critical section.
Definition at line 339 of file epoch_manager.h.
{
            epoch_manager::instance().exit_critical();
        }
References kcenon::container::epoch_manager::exit_critical(), and kcenon::container::epoch_manager::instance().
epoch_guard() [2/3]
kcenon::container::epoch_guard::epoch_guard (const epoch_guard &) delete
epoch_guard() [3/3]
kcenon::container::epoch_guard::epoch_guard (epoch_guard &&) delete
Member Function Documentation
operator=() [1/2]
epoch_guard & kcenon::container::epoch_guard::operator= (const epoch_guard &) delete
operator=() [2/2]
epoch_guard & kcenon::container::epoch_guard::operator= (epoch_guard &&) delete
The documentation for this class was generated from the following file:
internal/epoch_manager.h