Container System: kcenon::container::simd::simd_support Class Reference
kcenon::container::simd::simd_support Class Reference
Utility to check SIMD support at runtime.
#include <simd_processor.h>
Static Public Member Functions
static bool has_sse2 ()
static bool has_sse42 ()
static bool has_avx2 ()
static bool has_avx512f ()
static bool has_avx512dq ()
static bool has_avx512bw ()
static bool has_avx512vl ()
static bool has_neon ()
static simd_level get_best_simd_level ()
Get the best available SIMD instruction set level.
static std::string get_simd_info ()
Get a string describing available SIMD features.
static size_t get_optimal_width ()
Get the optimal SIMD width for current platform.
Detailed Description
Utility to check SIMD support at runtime.
Definition at line 275 of file simd_processor.h.
Member Function Documentation
get_best_simd_level()
simd_level kcenon::container::simd::simd_support::get_best_simd_level () static
Get the best available SIMD instruction set level.
Definition at line 649 of file simd_processor.cpp.
    {
        #if defined(HAS_ARM_NEON)
            return simd_level::neon;
        #endif
        if (has_avx512f()) return simd_level::avx512;
        if (has_avx2()) return simd_level::avx2;
        if (has_sse42()) return simd_level::sse42;
        if (has_sse2()) return simd_level::sse2;
        return simd_level::none;
    }
References kcenon::container::simd::avx2, kcenon::container::simd::avx512, has_avx2(), has_avx512f(), has_sse2(), has_sse42(), kcenon::container::simd::neon, kcenon::container::simd::none, kcenon::container::simd::sse2, and kcenon::container::simd::sse42.
get_optimal_width()
static size_t kcenon::container::simd::simd_support::get_optimal_width () inline static
Get the optimal SIMD width for current platform.
Definition at line 300 of file simd_processor.h.
{
            #if defined(HAS_AVX512)
                return 16;
            #elif defined(HAS_AVX2)
                return 8;
            #elif defined(HAS_SSE42) || defined(HAS_SSE2) || defined(HAS_ARM_NEON)
                return 4;
            #else
                return 1;
            #endif
        }
Referenced by get_simd_info().
get_simd_info()
std::string kcenon::container::simd::simd_support::get_simd_info () static
Get a string describing available SIMD features.
Definition at line 670 of file simd_processor.cpp.
    {
        std::string info = "SIMD Support: ";
        #if defined(HAS_AVX512)
            info += "AVX-512 ";
        #elif defined(HAS_AVX2)
            info += "AVX2 ";
        #elif defined(HAS_SSE42)
            info += "SSE4.2 ";
        #elif defined(HAS_SSE2)
            info += "SSE2 ";
        #elif defined(HAS_ARM_NEON)
            info += "NEON ";
        #else
            info += "None ";
        #endif
        // Add runtime detection info
        info += "(Compile-time), Runtime: ";
        if (has_avx512f()) {
            info += "AVX-512F ";
            if (has_avx512dq()) info += "AVX-512DQ ";
            if (has_avx512bw()) info += "AVX-512BW ";
            if (has_avx512vl()) info += "AVX-512VL ";
        } else if (has_avx2()) {
            info += "AVX2 ";
        } else if (has_sse42()) {
            info += "SSE4.2 ";
        } else if (has_sse2()) {
            info += "SSE2 ";
        } else if (has_neon()) {
            info += "NEON ";
        } else {
            info += "None ";
        }
        info += "(Width: " + std::to_string(get_optimal_width()) + ")";
        return info;
    }
References get_optimal_width(), has_avx2(), has_avx512bw(), has_avx512dq(), has_avx512f(), has_avx512vl(), has_neon(), has_sse2(), and has_sse42().
has_avx2()
bool kcenon::container::simd::simd_support::has_avx2 () static
Definition at line 584 of file simd_processor.cpp.
    {
        #if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86)
            #if defined(__GNUC__) || defined(__clang__)
                unsigned int eax, ebx, ecx, edx;
                if (__get_cpuid_count(7, 0, &eax, &ebx, &ecx, &edx)) {
                    return (ebx & (1 << 5)) != 0; // AVX2 bit
                }
            #endif
        #endif
        return false;
    }
Referenced by get_best_simd_level(), and get_simd_info().
has_avx512bw()
bool kcenon::container::simd::simd_support::has_avx512bw () static
Definition at line 623 of file simd_processor.cpp.
    {
        #if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86)
            #if defined(__GNUC__) || defined(__clang__)
                unsigned int eax, ebx, ecx, edx;
                if (__get_cpuid_count(7, 0, &eax, &ebx, &ecx, &edx)) {
                    return (ebx & (1 << 30)) != 0; // AVX-512BW bit
                }
            #endif
        #endif
        return false;
    }
Referenced by get_simd_info().
has_avx512dq()
bool kcenon::container::simd::simd_support::has_avx512dq () static
Definition at line 610 of file simd_processor.cpp.
    {
        #if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86)
            #if defined(__GNUC__) || defined(__clang__)
                unsigned int eax, ebx, ecx, edx;
                if (__get_cpuid_count(7, 0, &eax, &ebx, &ecx, &edx)) {
                    return (ebx & (1 << 17)) != 0; // AVX-512DQ bit
                }
            #endif
        #endif
        return false;
    }
Referenced by get_simd_info().
has_avx512f()
bool kcenon::container::simd::simd_support::has_avx512f () static
Definition at line 597 of file simd_processor.cpp.
    {
        #if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86)
            #if defined(__GNUC__) || defined(__clang__)
                unsigned int eax, ebx, ecx, edx;
                if (__get_cpuid_count(7, 0, &eax, &ebx, &ecx, &edx)) {
                    return (ebx & (1 << 16)) != 0; // AVX-512F bit
                }
            #endif
        #endif
        return false;
    }
Referenced by get_best_simd_level(), and get_simd_info().
has_avx512vl()
bool kcenon::container::simd::simd_support::has_avx512vl () static
Definition at line 636 of file simd_processor.cpp.
    {
        #if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86)
            #if defined(__GNUC__) || defined(__clang__)
                unsigned int eax, ebx, ecx, edx;
                if (__get_cpuid_count(7, 0, &eax, &ebx, &ecx, &edx)) {
                    return (ebx & (1 << 31)) != 0; // AVX-512VL bit
                }
            #endif
        #endif
        return false;
    }
Referenced by get_simd_info().
has_neon()
bool kcenon::container::simd::simd_support::has_neon () static
Definition at line 661 of file simd_processor.cpp.
    {
        #if defined(HAS_ARM_NEON)
            return true;
        #else
            return false;
        #endif
    }
Referenced by get_simd_info().
has_sse2()
bool kcenon::container::simd::simd_support::has_sse2 () static
Definition at line 558 of file simd_processor.cpp.
    {
        #if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86)
            #if defined(__GNUC__) || defined(__clang__)
                unsigned int eax, ebx, ecx, edx;
                if (__get_cpuid(1, &eax, &ebx, &ecx, &edx)) {
                    return (edx & (1 << 26)) != 0; // SSE2 bit
                }
            #endif
        #endif
        return false;
    }
Referenced by get_best_simd_level(), and get_simd_info().
has_sse42()
bool kcenon::container::simd::simd_support::has_sse42 () static
Definition at line 571 of file simd_processor.cpp.
    {
        #if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86)
            #if defined(__GNUC__) || defined(__clang__)
                unsigned int eax, ebx, ecx, edx;
                if (__get_cpuid(1, &eax, &ebx, &ecx, &edx)) {
                    return (ecx & (1 << 20)) != 0; // SSE4.2 bit
                }
            #endif
        #endif
        return false;
    }
Referenced by get_best_simd_level(), and get_simd_info().
The documentation for this class was generated from the following files:
internal/simd_processor.h
internal/simd_processor.cpp