Container System: kcenon::container::internal::pool_allocator Class Reference
kcenon::container::internal::pool_allocator Class Reference
Thread-local pool manager for value_container allocations.
#include <pool_allocator.h>
Public Member Functions
void * allocate (std::size_t size) noexcept
Allocate memory from the appropriate pool.
void deallocate (void *ptr, std::size_t size) noexcept
Deallocate memory to the appropriate pool.
pool_allocator_stats get_stats () const noexcept
Get allocation statistics.
fixed_block_pool::statistics get_small_pool_stats () const
Get statistics from the small pool.
fixed_block_pool::statistics get_medium_pool_stats () const
Get statistics from the medium pool.
void reset_stats () noexcept
Reset statistics (for benchmarking)
Static Public Member Functions
static pool_allocator & instance () noexcept
Get the singleton instance.
Private Member Functions
pool_allocator ()
pool_allocator (const pool_allocator &)=delete
pool_allocator & operator= (const pool_allocator &)=delete
pool_allocator (pool_allocator &&)=delete
pool_allocator & operator= (pool_allocator &&)=delete
Private Attributes
fixed_block_pool small_pool_
fixed_block_pool medium_pool_
pool_allocator_stats stats_
Detailed Description
Thread-local pool manager for value_container allocations.
Manages two size-class pools (small and medium) with thread-local instances for lock-free allocation on the fast path.
Definition at line 86 of file pool_allocator.h.
Constructor & Destructor Documentation
pool_allocator() [1/3]
kcenon::container::internal::pool_allocator::pool_allocator () inline private
Definition at line 186 of file pool_allocator.h.
        : small_pool_(pool_size_class::small_threshold, pool_size_class::blocks_per_chunk)
        , medium_pool_(pool_size_class::medium_threshold, pool_size_class::blocks_per_chunk)
    {}
pool_allocator() [2/3]
kcenon::container::internal::pool_allocator::pool_allocator (const pool_allocator &) private delete
pool_allocator() [3/3]
kcenon::container::internal::pool_allocator::pool_allocator (pool_allocator &&) private delete
Member Function Documentation
allocate()
void * kcenon::container::internal::pool_allocator::allocate (std::size_t size) inline noexcept
Allocate memory from the appropriate pool.
Parameters
size Number of bytes to allocate
Returns
Pointer to allocated memory, or nullptr on failure
Definition at line 102 of file pool_allocator.h.
{
        if (size == 0) {
            return nullptr;
        }
#if CONTAINER_USE_MEMORY_POOL
        try {
            if (size <= pool_size_class::small_threshold) {
                void* ptr = small_pool_.allocate();
                stats_.pool_hits++;
                stats_.small_pool_allocs++;
                return ptr;
            } else if (size <= pool_size_class::medium_threshold) {
                void* ptr = medium_pool_.allocate();
                stats_.pool_hits++;
                stats_.medium_pool_allocs++;
                return ptr;
            }
        } catch (...) {
            // Pool allocation failed, fall through to heap
        }
#endif
        // Large allocation or pool disabled: use heap
        stats_.pool_misses++;
        return ::operator new(size, std::nothrow);
    }
References kcenon::container::internal::fixed_block_pool::allocate(), medium_pool_, kcenon::container::internal::pool_allocator_stats::medium_pool_allocs, kcenon::container::internal::pool_size_class::medium_threshold, kcenon::container::internal::pool_allocator_stats::pool_hits, kcenon::container::internal::pool_allocator_stats::pool_misses, small_pool_, kcenon::container::internal::pool_allocator_stats::small_pool_allocs, kcenon::container::internal::pool_size_class::small_threshold, and stats_.
Referenced by kcenon::container::internal::pool_allocate().
deallocate()
void kcenon::container::internal::pool_allocator::deallocate (void * ptr, std::size_t size) inline noexcept
Deallocate memory to the appropriate pool.
Parameters
ptr Pointer to deallocate
size Size of the allocation
Definition at line 134 of file pool_allocator.h.
{
        if (!ptr) {
            return;
        }
        stats_.deallocations++;
#if CONTAINER_USE_MEMORY_POOL
        if (size <= pool_size_class::small_threshold) {
            small_pool_.deallocate(ptr);
            return;
        } else if (size <= pool_size_class::medium_threshold) {
            medium_pool_.deallocate(ptr);
            return;
        }
#endif
        // Large allocation: use heap
        ::operator delete(ptr);
    }
References kcenon::container::internal::fixed_block_pool::deallocate(), kcenon::container::internal::pool_allocator_stats::deallocations, medium_pool_, kcenon::container::internal::pool_size_class::medium_threshold, small_pool_, kcenon::container::internal::pool_size_class::small_threshold, and stats_.
Referenced by kcenon::container::internal::pool_allocate(), and kcenon::container::internal::pool_deallocate().
get_medium_pool_stats()
fixed_block_pool::statistics kcenon::container::internal::pool_allocator::get_medium_pool_stats () const inline
Get statistics from the medium pool.
Returns
Medium pool statistics
Definition at line 174 of file pool_allocator.h.
{
        return medium_pool_.get_statistics();
    }
References kcenon::container::internal::fixed_block_pool::get_statistics(), and medium_pool_.
get_small_pool_stats()
fixed_block_pool::statistics kcenon::container::internal::pool_allocator::get_small_pool_stats () const inline
Get statistics from the small pool.
Returns
Small pool statistics
Definition at line 166 of file pool_allocator.h.
{
        return small_pool_.get_statistics();
    }
References kcenon::container::internal::fixed_block_pool::get_statistics(), and small_pool_.
get_stats()
pool_allocator_stats kcenon::container::internal::pool_allocator::get_stats () const inline noexcept
Get allocation statistics.
Returns
Current statistics
Definition at line 158 of file pool_allocator.h.
{
        return stats_;
    }
References stats_.
instance()
static pool_allocator & kcenon::container::internal::pool_allocator::instance () inline static noexcept
Get the singleton instance.
Returns
Reference to thread-local pool allocator
Definition at line 92 of file pool_allocator.h.
{
        thread_local pool_allocator allocator;
        return allocator;
    }
Referenced by kcenon::container::internal::pool_allocate(), and kcenon::container::internal::pool_deallocate().
operator=() [1/2]
pool_allocator & kcenon::container::internal::pool_allocator::operator= (const pool_allocator &) private delete
operator=() [2/2]
pool_allocator & kcenon::container::internal::pool_allocator::operator= (pool_allocator &&) private delete
reset_stats()
void kcenon::container::internal::pool_allocator::reset_stats () inline noexcept
Reset statistics (for benchmarking)
Definition at line 181 of file pool_allocator.h.
{
        stats_ = pool_allocator_stats{};
    }
References stats_.
Member Data Documentation
medium_pool_
fixed_block_pool kcenon::container::internal::pool_allocator::medium_pool_ private
Definition at line 198 of file pool_allocator.h.
Referenced by allocate(), deallocate(), and get_medium_pool_stats().
small_pool_
fixed_block_pool kcenon::container::internal::pool_allocator::small_pool_ private
Definition at line 197 of file pool_allocator.h.
Referenced by allocate(), deallocate(), and get_small_pool_stats().
stats_
pool_allocator_stats kcenon::container::internal::pool_allocator::stats_ private
Definition at line 199 of file pool_allocator.h.
Referenced by allocate(), deallocate(), get_stats(), and reset_stats().
The documentation for this class was generated from the following file:
internal/pool_allocator.h