name: Build-Ubuntu-Clang

on:
  push:
    branches:
      - main
      - upgrade-from-messaging-system
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_linux_clang:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      BUILD_TYPE: Release
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      VCPKG_FEATURE_FLAGS: "manifests,registries,versions,binarycaching"
      VCPKG_DEFAULT_TRIPLET: x64-linux
      CC: clang-15
      CXX: clang++-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: true
          clean: true
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential gdb pkg-config curl zip unzip tar autoconf automake autoconf-archive ninja-build
          sudo apt install -y clang-15 libc++-15-dev libc++abi-15-dev
          sudo apt install -y libgtest-dev libgmock-dev

      - name: Check architecture
        run: |
          if [ "$(uname -m)" = "aarch64" ]; then
            echo "VCPKG_FORCE_SYSTEM_BINARIES=arm" >> $GITHUB_ENV
          fi

      - name: Cache vcpkg
        uses: actions/cache@v4
        id: vcpkg-cache
        with:
          path: |
            ${{ github.workspace }}/vcpkg
            !${{ github.workspace }}/vcpkg/buildtrees
            !${{ github.workspace }}/vcpkg/packages
            !${{ github.workspace }}/vcpkg/downloads
          key: ${{ runner.os }}-clang-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-clang-vcpkg-

      - name: Setup vcpkg
        if: steps.vcpkg-cache.outputs.cache-hit != 'true'
        run: |
          if [ ! -d "${{ github.workspace }}/vcpkg" ]; then
            git clone --depth 1 https://github.com/Microsoft/vcpkg.git ${{ github.workspace }}/vcpkg
          fi
          ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh

      - name: Install vcpkg dependencies
        run: |
          export VCPKG_ROOT=${{ github.workspace }}/vcpkg
          $VCPKG_ROOT/vcpkg install --triplet=x64-linux

      - name: Configure CMake
        run: |
          cmake -B build \
            -S . \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DVCPKG_TARGET_TRIPLET=x64-linux \
            -DCMAKE_C_COMPILER=clang-15 \
            -DCMAKE_CXX_COMPILER=clang++-15 \
            -DENABLE_MESSAGING_FEATURES=ON \
            -DENABLE_PERFORMANCE_METRICS=ON \
            -DENABLE_EXTERNAL_INTEGRATION=ON \
            -DBUILD_CONTAINER_EXAMPLES=ON \
            -DBUILD_CONTAINER_SAMPLES=ON \
            -DUSE_UNIT_TEST=ON \
            -G Ninja

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel

      - name: Test
        working-directory: build
        run: |
          if [ -f "./bin/examples/messaging_integration_example" ]; then
            echo "Running messaging integration example..."
            ./bin/examples/messaging_integration_example
          fi

      - name: Static Analysis with Clang-Tidy
        run: |
          find . -name "*.cpp" -not -path "./build/*" -not -path "./vcpkg/*" | head -10 | \
          xargs clang-tidy-15 \
            -p build \
            --checks='-*,clang-analyzer-*,performance-*,readability-*' \
            --warnings-as-errors=false || true

