name: Windows-VS-Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_windows_vs:
    permissions:
      contents: read
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        platform: [x64, Win32]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-strict: true
          ssh-user: git
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          fetch-depth: 1
          fetch-tags: false
          show-progress: true
          lfs: false
          set-safe-directory: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'c8696863d371ab7f46e213d8f5ca923c4aef2a00'

      - name: Cache vcpkg packages
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.VCPKG_ROOT }}/installed
            ${{ env.VCPKG_ROOT }}/packages
          key: ${{ runner.os }}-vcpkg-${{ matrix.platform }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-${{ matrix.platform }}-

      - name: Install dependencies with vcpkg
        run: |
          vcpkg install --triplet ${{ matrix.platform }}-windows

      - name: Configure CMake
        run: |
          cmake -B build -G "Visual Studio 17 2022" -A ${{ matrix.platform }} `
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
            -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" `
            -DUSE_UNIT_TEST=ON `
            -DBUILD_CONTAINER_EXAMPLES=ON `
            -DBUILD_CONTAINER_SAMPLES=ON `
            -DENABLE_MESSAGING_FEATURES=ON `
            -DENABLE_PERFORMANCE_METRICS=ON `
            -DENABLE_EXTERNAL_INTEGRATION=ON

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Run Tests
        working-directory: build
        run: |
          ctest --build-config ${{ matrix.build_type }} --output-on-failure --verbose

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: container-system-windows-vs-${{ matrix.platform }}-${{ matrix.build_type }}
          path: |
            build/${{ matrix.build_type }}/*.lib
            build/${{ matrix.build_type }}/*.exe
            build/examples/${{ matrix.build_type }}/*.exe
          retention-days: 7

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-windows-vs-${{ matrix.platform }}-${{ matrix.build_type }}
          path: |
            build/Testing/
          retention-days: 3